### PR TITLE
Add offscreen surface types

### PR DESCRIPTION
**Pull request by ecoal95**
This commit adds the necessary options to support creating an offscreen context backed by a pixel buffer or a pixmap, which is needed for WebGL support on android.

### CODE REVIEW

**Comment by glennw** [comment]
@ecoal95 I'm pretty sure we don't use rust-egl now - it should be marked as unmaintained - we use the auto generated EGL bindings in glutin - see https://github.com/servo/glutin/blob/servo/build.rs#L63 for an example.

**Comment by ecoal95** [comment]
@glennw It's used, if I'm not wrong, in both azure and layers, repos that
shouldn't depend on glutin. I think using it in offscreen_gl_context makes
even more sense.

**Comment by glennw** [comment]
@ecoal95 You're quite right - my mistake. We should update those in the future to use the auto generated bindings like glutin does, but it's fine to merge this for now :)

**Comment by glennw** [comment]
r+

**Pull request merged**
